### ISSUE TITLE
Error when I change conf file

### ISSUE THREAD

**Issue by erinlee1109** [cosmeoes/keymapper#1]
Hello! Thanks for this cool project. When I run the program without changing the conf file (with everything commented), it runs successfully and the small keyboard icon appears. When I uncomment a = b on the .conf file, then run "sudo python keyMapper.pyw", I receive this error:  "NameError: name 'value' is not defined." Is this supported on M1? Perhaps I'm doing something wrong? Thanks! 

<img width="747" alt="Screen Shot 2021-04-06 at 1 48 47 PM" src="https://user-images.githubusercontent.com/55002541/113756205-20f91400-96df-11eb-86bc-ea84f81af379.png">
<img width="751" alt="Screen Shot 2021-04-06 at 1 49 57 PM" src="https://user-images.githubusercontent.com/55002541/113756212-2191aa80-96df-11eb-820b-080d0b1fe673.png">

**Comment by cosmeoes** [comment]
Hey, I fixed the issue. Please note that I only tested this on Linux and windows, I don't know if it works correctly on mac or M1 for that matter.
